baseURL = "https://edu.fintual.cl"
title = "EDU Fintual"
preserveTaxonomyNames = true
theme = "mediumish"
copyright = " 2019 | fintual.com "
languageCode = "es-cl"
summaryLength = 15
removePathAccents = false

[Permalinks]
 posts = "/:filename/"
[params]
image = "/img/fintualedu_screen.png"
author = "Equipo Fintual"
description = "Aprendiendo a invertir bien"
displayauthor = true
keywords = ["inversion", "fondos mutuos", "ahorro"]
logo = "img/logo.png"
sharingicons = false
  [params.writers]
    [params.writers."Pedro Pineda"]
    name = "Pedro Pineda"
    thumbnail = "/uploads/pedro.jpg"
    [params.writers."Agustín Feuerhake"]
    name = "Agustín Feuerhake"
    thumbnail = "/uploads/agustin.jpg"
    [params.writers."Andrés Marinkovic"]
    name = "Andrés Marinkovic"
    thumbnail = "/uploads/andres.jpg"
    [params.writers."Omar Larré"]
    name = "Omar Larré"
    thumbnail = "/uploads/omar.jpg"
    [params.writers."Gonzalo Enei"]
    name = "Gonzalo Enei"
    thumbnail = "/uploads/gonzalo.jpg"
    [params.writers."Francesca Finaldi"]
    name = "Francesca Finaldi"
    thumbnail = "/uploads/francesca.jpg"
    [params.writers."Francisca Feuerhake"]
    name = "Francisca Feuerhake"
    thumbnail = "/uploads/francisca_feuerhake.jpg"
    [params.writers."Juan Francisco Weitz"]
    name = "Juan Francisco Weitz"
    thumbnail = "/uploads/jf.png"
    [params.writers."Ignacia Palma"]
    name = "Ignacia Palma"
    thumbnail = "/uploads/ignacia.jpg"
    [params.writers."Cristóbal Fredes"]
    name = "Cristóbal Fredes"
    thumbnail = "/uploads/cristobal_fredes.jpeg"
    [params.writers."Paula Droguett"]
    name= "Paula Droguett"
    thumbnail= "/uploads/paula_droguett.jpeg"
    [params.writers."Matías Hurtado"]
    name= "Matías Hurtado"
    thumbnail= "/uploads/matias.jpg"

[params.highlight]
languages = ["go", "dockerfile"]
style = "github"
[params.social]
  twitter = "fintual"
[taxonomies]
category = "categories"
tag = "tags"
[related]
threshold = 30.0
includeNewer = true
toLower = false
  # [[related.indices]]
  # name = "keywords"
  # weight = 70.0
  [[related.indices]]
  name = "date"
  weight = 30.0
  [[related.indices]]
  name = "categories"
  weight = 100.0
